### ISSUE TITLE
Could make custom icons in illustrator

### ISSUE THREAD

**Issue by kadenzipfel** [nerdwise/whelpton-electric#107]

**Comment by angusm** [comment]
If we do this let's get some sharper corners. Not sure how it works in illustrator but if we can match the border radius we use for the rest of the site on the corners here that'd be awesome. Right now they feel a bit too fisher price if that makes sense?

**Comment by kadenzipfel** [comment]
Custom icons done, just have to insert them

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/116
