### ISSUE TITLE
Inline services pop-ups

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#173]
The modal looks good and works great, but I think we can up our game a smidge further.

So rather than have a modal, let's have the Services sections become a small-button based nav bar at the top (w/ a slick transition of course).

Then users can see a carousel/gallery of images in-line in the page.
This will have a couple of advantages:
 - Users don't need to click to close to continue exploring the rest of the page
 - Users don't need to click to close to switch to another services section

Modals kind of trap the user and we want to try and avoid that if at all possible.

**Comment by kadenzipfel** [comment]
This sounds super cool and I agree with you on this. I'm just having a bit of trouble trying to visualize this. Do you happen to know of any examples?

**Comment by angusm** [comment]
Checkout the Front-End/Design/Branding section here: http://www.hanatelahun.ca/
But imagine instead of a drop down appearing, the service boxes get up and out of the way to become a sort of sub-header nav for a carousel between sections.

**Comment by kadenzipfel** [comment]
To make sure we're on the same page, here's a codepen I'm working on: https://codepen.io/kadenzipfel/pen/KEbRZV

Does this look about right?

**Comment by angusm** [comment]
Yes! That's exactly the idea :) Now the goal is to get it in the whelpton site looking slick with a real smooth transition.

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/176
