### ISSUE TITLE
services.onClick is not a function

### ISSUE THREAD

**Issue by kadenzipfel** [nerdwise/whelpton-electric#175]
For some reason the html onclick handler isn't picking up the Services onClick() method.

**Comment by kadenzipfel** [comment]
Possible work around would be to handle the click in typescript instead of the html with an addEventListener

**Comment by angusm** [comment]
Just a heads up that we don't want to use any HTML attribute event handlers. Ideally any code for interactions is kept in Typescript so that we only need to look in one place when debugging interactions.

**Comment by kadenzipfel** [comment]
Thanks for letting me know! All fixed up now
