### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#205]
All elements should have at least 8px of separation for content that is grouped together.

Separate elements should have at least 24px to breath.
Particularly logos in the nav.
When the nav is collapsed we can probably get away with 16px.

Footer as well.
Horizontal spacing of services tabs when open.

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/251

**Comment by angusm** [comment]
Footer still needs more breathing room above the logo and below the email

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/295
