### ISSUE TITLE
Projects page images alignment

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#218]
Let's crop to size and try and rotate for up-down left-right straight lines for both the thumbnails and full-views of images on the projects page.

Ideally the thumbnail and full-view image should be different images if they aren't already.

**Comment by angusm** [comment]
We want to use javascript so that the lightbox doesn't load the image ahead of us needing if we aren't already.

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/250
