### ISSUE TITLE
Project Pages Images consistent spacing

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#219]
We want the same horizontal and vertical margin between images on the project page so that they form a grid.

Center final line as needed, but the margins should be the same as lines above.

**Comment by angusm** [comment]
Follow-up with Hannah to get one more image so we have an even 15 for a nice looking grid.

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/249

**Comment by angusm** [comment]
This doesn't look fixed to me

**Comment by angusm** [comment]
The bottom row still has inconsistent horizontal spacing compared to the previous rows.
We'll need a fix for this. The solution is likely going to be using consistent margin and width, and using "justify-content: center"

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/296
