### ISSUE TITLE
Even more whitespace above and below logo in un-collapsed header

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#256]
Let's add another 8px on top and bottom.
Also possibly play with a version that puts the text to the right rather than on top.

Potentially even diamonds without the line and then "WHELPTON" to the right top with "electric" stacked below it.

**Comment by kadenzipfel** [comment]
So did we want whitespace between each element of the logo, or just the top and bottom?

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/295
