### ISSUE TITLE
Give services boxes height auto when shrunk

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#270]
Remove the margin from the title and put it as padding on the box at padding: 1rem.
Always display both icon and name.
Fix icon height at 48px
Adjust box content so that the body copy and image are always below the buttons no matter how tall or small we make them.

**Comment by kadenzipfel** [comment]
Need to make white versions of each icon to be able to display icon on active.

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/304
