### ISSUE TITLE
Mobile scroll-responsive nav

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#273]
Have nav slide up and out of the way when user is scrolling down and slide back in when user scrolls up on mobile.

Look at RemoveTransformOnScrollDown in toolbox

**Comment by kadenzipfel** [comment]
RemoveTransformOnScrollDown is actually a ScrollEffect, so it should be setup like any other scroll effect.

**Comment by kadenzipfel** [comment]
I'm getting this error: `Type 'void' is not assignable to type 'IEffect'.` when I run the method `run`, which is supposed to return void.

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/308
