### ISSUE TITLE
About/Services

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#290]
Something feels off with them.
Fully opaque feels like too plain, transparent with the mountain background feels a bit too busy. I don't know if the solution is a subtle gradient, or an inner box over top of a textured background? Like maybe services floats on an opaque piece that has margin on all sides where the mountain background is visible? If that works for Services we can reuse it for the About page?
Once we figure that out if Services feel too visually noisy we can try and be even more subtle with the gradient. I'm not sure what I want here but it doesn't quite feel perfect yet. It feels really good but we can get it better I think.

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/305
