### ISSUE TITLE
Give backgrounds subtle gradients

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#37]
Let's get some subtle gradients going.
Like these: https://medium.com/@colin_23042/subtle-text-gradient-effect-with-webkits-5017c6c36736
But subtler.

The goal is to have the design feel less flat but in a way that someone couldn't directly point to.

**Comment by angusm** [comment]
Oh-ho-ho! You've already done it on services!
Let's get _slightly_ less subtle than that and put the darker color on top.

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/56
