### ISSUE TITLE
Give E-mail / Call buttons some color pop

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#38]
We absolutely positively do not want visitors to miss these since they are the reason for all the rest of the site to exist. Our marketing sites exist only to drive conversion for the client, so we want to make sure the user never wonders how to get in touch.

Let's give these a bright color from the brand colors and a gradient border rim from the others.
Let's go with the green from the logo and the yellow for the rim.

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/63
