### ISSUE TITLE
Try some images from Whelpton Electric Images shared album

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#44]
Setup a shared album with some images to try: https://photos.google.com/share/AF1QipNHE935lTEXTRZFlK8r3h673tTldYVaq0xUrqo_V_Hd0z7ak7Wt9FCMfUqNWnA6Hw?key=NWx4ODktS0lWSEtKcVZzVGE1WlVDb3drUVZiRWNB

Play around, adjust in photoshop as needed, see if any crop of any of them look alright in the hero spot.

Cut some branches for your 3 favorites and drop screenshots here.

Photos in there are landscape shots of Agassiz where the company operates.

**Comment by angusm** [comment]
Also feel free to grab any generic mountain/clouds stock photography we're legally allowed to use and give that a shot.

**Comment by kadenzipfel** [comment]
I'm really fond of something like this https://imgur.com/a/Z0uPgnT

**Comment by kadenzipfel** [comment]
Perhaps even set the background image to position: fixed?

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/64 Not sure if I was meant to make it a separate component or not, but here's what I think works best

**Comment by kadenzipfel** [comment]
Might be better with a lower opacity to make content over top of it more readable
