### ISSUE TITLE
Consolidate font sizes

### ISSUE THREAD

**Issue by angusm** [nerdwise/whelpton-electric#67]
To make sure we have consistent typography let's get a config file going with a set number of font sizes. Probably also worth giving them purpose based names similar to the color config.

$header-font-size
$subheader-font-size
$body-font-size
$cta-font-size

And you'll probably need --desktop and --mobile variations for each.

**Comment by kadenzipfel** [comment]
--mobile variations will be added on mobile breakpoints branch

**Comment by kadenzipfel** [comment]
https://github.com/nerdwise/whelpton-electric/pull/70

**Comment by kadenzipfel** [comment]
Add --breakpoint variations before closing
